name: taskr
description: "A cross-platform to-do app"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^2.31.0
  cloud_firestore: ^4.17.3
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.7.0
  sign_in_with_apple: ^6.1.0
  google_sign_in: ^6.2.1
  firebase_auth: ^4.19.5
  json_annotation: ^4.9.0
  rxdart: ^0.27.7
  provider: ^6.1.2
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.10


flutter:
  uses-material-design: true

  assets:
    - assets/
    - .env