// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdPnIFovrJzzGK0yHLdGs9UKA3CkmwoR8',
    appId: '1:1070956843093:web:1c4946ee7d1442116604dc',
    messagingSenderId: '1070956843093',
    projectId: 'taskr-1428',
    authDomain: 'taskr-1428.firebaseapp.com',
    storageBucket: 'taskr-1428.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp3fTO2bR6qpwAKXG6itbssRhWzT7x7l8',
    appId: '1:1070956843093:android:8be9d4f73f5570296604dc',
    messagingSenderId: '1070956843093',
    projectId: 'taskr-1428',
    storageBucket: 'taskr-1428.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXA79gRO_PXwxKS913S10f66AWjUYCaH0',
    appId: '1:1070956843093:ios:0e47d33d6dd0323c6604dc',
    messagingSenderId: '1070956843093',
    projectId: 'taskr-1428',
    storageBucket: 'taskr-1428.appspot.com',
    iosBundleId: 'com.example.taskr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXA79gRO_PXwxKS913S10f66AWjUYCaH0',
    appId: '1:1070956843093:ios:0e47d33d6dd0323c6604dc',
    messagingSenderId: '1070956843093',
    projectId: 'taskr-1428',
    storageBucket: 'taskr-1428.appspot.com',
    iosBundleId: 'com.example.taskr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdPnIFovrJzzGK0yHLdGs9UKA3CkmwoR8',
    appId: '1:1070956843093:web:60c8fdeed0c21f366604dc',
    messagingSenderId: '1070956843093',
    projectId: 'taskr-1428',
    authDomain: 'taskr-1428.firebaseapp.com',
    storageBucket: 'taskr-1428.appspot.com',
  );
}
